/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./../components/Badge.vue')['default']
    HBadge: typeof import('./../components/HBadge.vue')['default']
    ReportView: typeof import('./../components/ReportView.vue')['default']
  }
}
